"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class CollectionStatus(str, Enum):
    r"""Current state of the collection. `Green` - all good. `Yellow` - optimization is running, `Red` - some operations failed and was not recovered"""
    GREEN = 'green'
    YELLOW = 'yellow'
    RED = 'red'
