"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import collectiondescription as shared_collectiondescription
from dataclasses_json import Undefined, dataclass_json
from sdk import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class CollectionsResponse:
    collections: list[shared_collectiondescription.CollectionDescription] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('collections') }})
    

