"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import createalias as shared_createalias
from dataclasses_json import Undefined, dataclass_json
from sdk import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreateAliasOperation:
    r"""Group of all the possible operations related to collection aliases"""
    
    create_alias: shared_createalias.CreateAlias = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('create_alias') }})
    r"""Create alternative name for a collection. Collection will be available under both names for search, retrieve,"""
    