"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import deletealias as shared_deletealias
from dataclasses_json import Undefined, dataclass_json
from sdk import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class DeleteAliasOperation:
    r"""Delete alias if exists"""
    
    delete_alias: shared_deletealias.DeleteAlias = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('delete_alias') }})
    r"""Delete alias if exists"""
    