"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class DistanceEnum(str, Enum):
    r"""Type of internal tags, build from payload Distance function types used to compare vectors"""
    COSINE = 'Cosine'
    EUCLID = 'Euclid'
    DOT = 'Dot'
