"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import geopoint as shared_geopoint
from dataclasses_json import Undefined, dataclass_json
from sdk import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class GeoBoundingBox:
    r"""Geo filter request
    
    Matches coordinates inside the rectangle, described by coordinates of lop-left and bottom-right edges
    """
    
    bottom_right: shared_geopoint.GeoPoint = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('bottom_right') }})
    r"""Geo point payload schema"""  
    top_left: shared_geopoint.GeoPoint = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('top_left') }})
    r"""Geo point payload schema"""  
    