"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import geopoint as shared_geopoint
from dataclasses_json import Undefined, dataclass_json
from sdk import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class GeoRadius:
    r"""Geo filter request
    
    Matches coordinates inside the circle of `radius` and center with coordinates `center`
    """
    center: shared_geopoint.GeoPoint = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('center') }})
    r"""Geo point payload schema"""
    radius: float = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('radius') }})
    r"""Radius of the area in meters"""
    

