"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import payloadfield as shared_payloadfield
from dataclasses_json import Undefined, dataclass_json
from sdk import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class IsEmptyCondition:
    r"""Select points with empty payload for a specified field"""
    
    is_empty: shared_payloadfield.PayloadField = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('is_empty') }})

    r"""Payload field"""
    