"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import replicastate_enum as shared_replicastate_enum
from dataclasses_json import Undefined, dataclass_json
from sdk import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class LocalShardInfo:
    
    points_count: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('points_count') }})
    r"""Number of points in the shard"""  
    shard_id: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('shard_id') }})
    r"""Local shard id"""  
    state: shared_replicastate_enum.ReplicaStateEnum = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('state') }})
    r"""State of the single shard within a replica set."""  
    