"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class PayloadSchemaTypeEnum(str, Enum):
    r"""All possible names of payload types"""
    KEYWORD = 'keyword'
    INTEGER = 'integer'
    FLOAT = 'float'
    GEO = 'geo'
    TEXT = 'text'
