"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ReadConsistencyType(str, Enum):
    r"""* `majority` - send N/2+1 random request and return points, which present on all of them
    
    * `quorum` - send requests to all nodes and return points which present on majority of nodes
    
    * `all` - send requests to all nodes and return points which present on all nodes
    """
    MAJORITY = 'majority'
    QUORUM = 'quorum'
    ALL = 'all'
