"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import renamealias as shared_renamealias
from dataclasses_json import Undefined, dataclass_json
from sdk import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class RenameAliasOperation:
    r"""Change alias to a new one"""
    rename_alias: shared_renamealias.RenameAlias = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('rename_alias') }})
    r"""Change alias to a new one"""
    

