"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ReplicaState(str, Enum):
    r"""State of the single shard within a replica set."""
    ACTIVE = 'Active'
    DEAD = 'Dead'
    PARTIAL = 'Partial'
    INITIALIZING = 'Initializing'
    LISTENER = 'Listener'
