"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class SegmentTypeEnum(str, Enum):
    r"""Type of segment"""
    PLAIN = 'plain'
    INDEXED = 'indexed'
    SPECIAL = 'special'
