"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import payloadindextelemetry as shared_payloadindextelemetry
from ..shared import segmentconfig as shared_segmentconfig
from ..shared import segmentinfo as shared_segmentinfo
from ..shared import vectorindexsearchestelemetry as shared_vectorindexsearchestelemetry
from dataclasses_json import Undefined, dataclass_json
from sdk import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class SegmentTelemetry:
    
    config: shared_segmentconfig.SegmentConfig = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('config') }})
    info: shared_segmentinfo.SegmentInfo = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('info') }})
    r"""Aggregated information about segment"""
    payload_field_indices: list[shared_payloadindextelemetry.PayloadIndexTelemetry] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('payload_field_indices') }})
    vector_index_searches: list[shared_vectorindexsearchestelemetry.VectorIndexSearchesTelemetry] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('vector_index_searches') }})
    