"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class StateRoleEnum(str, Enum):
    r"""Role of the peer in the consensus"""
    FOLLOWER = 'Follower'
    CANDIDATE = 'Candidate'
    LEADER = 'Leader'
    PRE_CANDIDATE = 'PreCandidate'
