"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import appbuildtelemetry as shared_appbuildtelemetry
from ..shared import clustertelemetry as shared_clustertelemetry
from ..shared import collectionstelemetry as shared_collectionstelemetry
from ..shared import requeststelemetry as shared_requeststelemetry
from dataclasses_json import Undefined, dataclass_json
from sdk import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class TelemetryData:
    
    app: shared_appbuildtelemetry.AppBuildTelemetry = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('app') }})

    cluster: shared_clustertelemetry.ClusterTelemetry = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('cluster') }})

    collections: shared_collectionstelemetry.CollectionsTelemetry = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('collections') }})

    id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})

    requests: shared_requeststelemetry.RequestsTelemetry = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('requests') }})

    