"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class TokenizerTypeEnum(str, Enum):
    PREFIX = 'prefix'
    WHITESPACE = 'whitespace'
    WORD = 'word'
