"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class UpdateStatus(str, Enum):
    r"""`Acknowledged` - Request is saved to WAL and will be process in a queue. `Completed` - Request is completed, changes are actual."""
    ACKNOWLEDGED = 'acknowledged'
    COMPLETED = 'completed'
