"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class WriteOrderingEnum(str, Enum):
    r"""Defines write ordering guarantees for collection operations
    
    * `weak` - write operations may be reordered, works faster, default
    
    * `medium` - write operations go through dynamically selected leader, may be inconsistent for a short period of time in case of leader change
    
    * `strong` - Write operations go through the permanent leader, consistent, but may be unavailable if leader is down
    """
    WEAK = 'weak'
    MEDIUM = 'medium'
    STRONG = 'strong'
