"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Optional


@dataclasses.dataclass
class MetricsRequest:
    
    anonymize: Optional[bool] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'anonymize', 'style': 'form', 'explode': True }})
    r"""If true, anonymize result"""
    

@dataclasses.dataclass
class MetricsResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    metrics_200_text_plain_string: Optional[str] = dataclasses.field(default=None)
    r"""Metrics data in Prometheus format"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    